# Generated by Django 4.2.8 on 2024-04-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=600)),
                ('yes', models.CharField(max_length=200)),
                ('no', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('typeof', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
