# Generated by Django 4.1 on 2024-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_testgayss_result_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgayss',
            name='date',
            field=models.DateField(),
        ),
    ]
