# Generated by Django 4.1 on 2024-05-23 05:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_testgayss_password_testgayss_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='note',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testgayss',
            name='who',
            field=models.CharField(choices=[('Phụ huynh', 'Phụ huynh'), ('Giáo viên', 'Giáo viên')], default=None, max_length=200),
        ),
    ]
